name = "Julia4ML_GA"
uuid = "bf3591ee-69f7-4669-bac3-51a98216d305"
authors = ["Jonas Engler <jonas.engler@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6.7"
