name = "Julia4ML_GA"
uuid = "bf3591ee-69f7-4669-bac3-51a98216d305"
authors = ["Ben Nikolas Baute <baute@campus.tu-berlin.de>", "Jonas Engler <jonas.engler@campus.tu-berlin.de>", "Anja Katharina Ilg <ilg@campus.tu-berlin.de>", "Nicolas Oliver Julian Look <n.look@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6.7"
